{
 "title": "Speedtest MongoDB",
 "description": "Dashboard to visualize Ookla speedtest data published on a MongoDB database",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Bandwidth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bandwidth Graph",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "db.normalized_speedtest.aggregate([{\n        \"$match\": {\n            \"ts\": {\n                \"$gte\": \"$from\",\n                \"$lte\": \"$to\"\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"ts\": 1\n        }\n    },\n    {\n        \"$project\": {\n            \"name\": \"download\",\n            \"value\": \"$downloadMbps\",\n            \"ts\": \"$ts\",\n            \"_id\": 0\n        }\n    }\n])",
     "type": "timeserie"
    },
    {
     "target": "db.normalized_speedtest.aggregate([{\n        \"$match\": {\n            \"ts\": {\n                \"$gte\": \"$from\",\n                \"$lte\": \"$to\"\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"ts\": 1\n        }\n    },\n    {\n        \"$project\": {\n            \"name\": \"upload\",\n            \"value\": \"$uploadMbps\",\n            \"ts\": \"$ts\",\n            \"_id\": 0\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Download Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.normalized_speedtest.aggregate([{\n        \"$match\": {\n            \"ts\": {\n                \"$gte\": \"$from\",\n                \"$lte\": \"$to\"\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"ts\": 1\n        }\n    },\n    {\n        \"$project\": {\n            \"name\": \"download\",\n            \"value\": \"$downloadMbps\",\n            \"ts\": \"$ts\",\n            \"_id\": 0\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Upload Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.normalized_speedtest.aggregate([{\n        \"$match\": {\n            \"ts\": {\n                \"$gte\": \"$from\",\n                \"$lte\": \"$to\"\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"ts\": 1\n        }\n    },\n    {\n        \"$project\": {\n            \"name\": \"upload\",\n            \"value\": \"$uploadMbps\",\n            \"ts\": \"$ts\",\n            \"_id\": 0\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  },
  { "title": "Packets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Ping",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.normalized_speedtest.aggregate([{\n        \"$match\": {\n            \"ts\": {\n                \"$gte\": \"$from\",\n                \"$lte\": \"$to\"\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"ts\": 1\n        }\n    },\n    {\n        \"$project\": {\n            \"name\": \"ping latency\",\n            \"value\": \"$pingLatency\",\n            \"ts\": \"$ts\",\n            \"_id\": 0\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.normalized_speedtest.aggregate([{\n        \"$match\": {\n            \"ts\": {\n                \"$gte\": \"$from\",\n                \"$lte\": \"$to\"\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"ts\": 1\n        }\n    },\n    {\n        \"$project\": {\n            \"name\": \"ping jitter\",\n            \"value\": \"$pingJitter\",\n            \"ts\": \"$ts\",\n            \"_id\": 0\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "db.normalized_speedtest.aggregate([{\n        \"$match\": {\n            \"ts\": {\n                \"$gte\": \"$from\",\n                \"$lte\": \"$to\"\n            }\n        }\n    },\n    {\n        \"$sort\": {\n            \"ts\": 1\n        }\n    },\n    {\n        \"$project\": {\n            \"name\": \"packe loss\",\n            \"value\": \"$packetLoss\",\n            \"ts\": \"$ts\",\n            \"_id\": 0\n        }\n    }\n])",
     "type": "timeserie"
    }
   ]
  }
 ]
}